pipeline
{
    agent { label 'linux'}

    stages
    {
    

        
        stage('clean workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Set requirements')
        {
            steps
            {
                sh """
                poetry env use python3.8
                poetry install -v --no-ansi --no-interaction
                """
            }
        }
     
    
        stage('Terraform')
        {
            when
            {
                branch 'main'
            }
            steps
            {
                dir('terraform deploy')
                {
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding'])
                    {
                        
                        
                          sh "terraform init"
                          sh "terraform validate"
                          sh "terraform plan -out plan -var function_version=${RELEASE_NAME}"
                          sh "terraform apply -input=false plan"
                        
                    }
                }
            }
        }
        stage('Run Integration tests')
        {
            when
            {
                branch 'main'
            }
            steps
            {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding']])
                {
                      sh """
                      . \$(poetry env info --path)/bin/activate
                      AWS_DEFAULT_REGION=eu-west-1 pytest -v ./tests
                      """
                }
            }
     
       }
    }
}
        